// File Autogenerated by TypeRight.  DO NOT EDIT
import { callPost } from "../CallServiceStuff";
/**
 *
 * @param model
 */
export function AnonTypeWithDictionaryProperty(model, abort) {
    return callPost("/Home/AnonTypeWithDictionaryProperty", model, abort);
}
/**
 *
 * @param model
 */
export function FunctionWithModel(model, abort) {
    return callPost("/Home/FunctionWithModel", model, abort);
}
/**
 *
 * @param model
 */
export function OtherFunctionWithModel(model, abort) {
    return callPost("/Home/OtherFunctionWithModel", model, abort);
}
/**
 *
 */
export function TestJson(abort) {
    return callPost("/Home/TestJson", {}, abort);
}
//# sourceMappingURL=HomeActions.js.map