// File Autogenerated by TypeRight.  DO NOT EDIT
import { callPost } from "../CallServiceStuff";
import * as ServerObjects from "../ServerObjects";
import * as CustomGroup from "../CustomGroup";
import * as Models from "./Models";


/**
 * 
 * @param model 
 */
export function AnonTypeWithDictionaryProperty(model: Models.CustomGroupObj3, abort?: AbortSignal): Promise<{ listObj: CustomGroup.CustomGroupObject1[] }> {
	return callPost("/Home/AnonTypeWithDictionaryProperty", model, abort);
}

/**
 * 
 * @param model 
 */
export function FunctionWithModel(model: ServerObjects.ASimpleModel, abort?: AbortSignal): Promise<ServerObjects.ASimpleModel> {
	return callPost("/Home/FunctionWithModel", model, abort);
}

/**
 * 
 * @param model 
 */
export function OtherFunctionWithModel(model: CustomGroup.CustomGroupObject1, abort?: AbortSignal): Promise<CustomGroup.CustomGroupObject1> {
	return callPost("/Home/OtherFunctionWithModel", model, abort);
}

/**
 * 
 */
export function TestJson(abort?: AbortSignal): Promise<ServerObjects.NetStandardClass> {
	return callPost("/Home/TestJson", { }, abort);
}


