// File Autogenerated by TypeRight.  DO NOT EDIT
import { callService } from "../CallServiceStuff";
import * as ServerObjects from "../ServerObjects";
import * as CustomGroup from "../CustomGroup";
import * as Models from "./Models";


/**
 * 
 * @param model 
 */
export function AnonTypeWithDictionaryProperty(model: Models.CustomGroupObj3, success?: (result: { listObj: CustomGroup.CustomGroupObject1[] }) => void, fail?: (result: any) => void): void {
	callService("/Home/AnonTypeWithDictionaryProperty", model, success, fail);
}

/**
 * 
 * @param model 
 */
export function FunctionWithModel(model: ServerObjects.ASimpleModel, success?: (result: ServerObjects.ASimpleModel) => void, fail?: (result: any) => void): void {
	callService("/Home/FunctionWithModel", model, success, fail);
}

/**
 * 
 * @param model 
 */
export function OtherFunctionWithModel(model: CustomGroup.CustomGroupObject1, success?: (result: CustomGroup.CustomGroupObject1) => void, fail?: (result: any) => void): void {
	callService("/Home/OtherFunctionWithModel", model, success, fail);
}

/**
 * 
 */
export function TestJson(success?: (result: ServerObjects.NetStandardClass) => void, fail?: (result: any) => void): void {
	callService("/Home/TestJson", { }, success, fail);
}


