// File Autogenerated by TypeRight.  DO NOT EDIT
import * as ServerObjects from "ServerObjects";

// ===============================
// Classes
// ===============================
/**  */
export interface ASimpleModel<T1, T2> {
	/**  */
	Reference: ServerObjects.ASimpleModel_1<T1>;
	/**  */
	AhDoesThisWork: ASimpleEnum;
}

/**  */
export interface CustomGroupObj2 {
	/**  */
	Obj1: CustomGroupObject1;
}

/**  */
export interface CustomGroupObj2_1<T> {
	/**  */
	Property: number;
}

/**  */
export interface CustomGroupObject1 {
	/** Add doc */
	Prop1: number;
	/**  */
	OtherClass: ServerObjects.NetStandardClass;
	/** Just has a string list */
	AnotherStringList: string[];
}

  

// ===============================
// Enums
// ===============================

/**  */
export enum ASimpleEnum {
	/**  */
	A = 0,
	/**  */
	B = 1,
	/**  */
	C = 2,
}
 

  