// File Autogenerated by TypeRight.  DO NOT EDIT

// ===============================
// Classes
// ===============================
/** Tst model */
export interface ASimpleModel {
	/** Doc for prop 1 */
	PropOne: number;
	/** Doc for prop 2 */
	PropTwo: string;
}

/** Test summ */
export interface ErrorViewModel {
	/**  */
	RequestId: string;
	/**  */
	ShowRequestId: boolean;
}

/**  */
export interface GenericModel<T> {
}

/** Start some doc here */
export interface NetStandardClass {
	/**  */
	HelloThere: number;
}

/**  */
export interface TestTwoTypeParams<T, T2> {
}

  

// ===============================
// Enums
// ===============================
  