// File Autogenerated by TypeRight.  DO NOT EDIT

// ===============================
// Classes
// ===============================
/**  */
export interface ASimpleModel {
	/**  */
	PropOne: number;
	/**  */
	PropTwo: string;
}

/** Test summ */
export interface ErrorViewModel {
	/**  */
	RequestId: string;
	/**  */
	ShowRequestId: boolean;
}

/** Start some doc here */
export interface NetStandardClass {
	/**  */
	HelloThere: number;
}

  

// ===============================
// Enums
// ===============================
  