// File Autogenerated by TypeRight.  DO NOT EDIT

// ===============================
// Classes
// ===============================
/** Test summ */
export interface ErrorViewModel {
	/**  */
	RequestId: string;
	/**  */
	ShowRequestId: boolean;
}

  

// ===============================
// Enums
// ===============================
  