// File Autogenerated by TypeRight.  DO NOT EDIT
import { fetchWrapper } from "../CallServiceStuff";
import * as CustomGroup from "../CustomGroup";
import * as ServerObjects from "../ServerObjects";
import * as Models from "./Models";


/**
 * 
 * @param model 
 */
export function AnonTypeWithDictionaryProperty(model: Models.CustomGroupObj3, abort?: AbortSignal): Promise<{ listObj: CustomGroup.CustomGroupObject1[] }> {
	return fetchWrapper("GET", `/Home/AnonTypeWithDictionaryProperty?param1=val1&param2=val2`, model, abort);
}

/**
 * 
 * @param model 
 */
export function FunctionWithModel(model: ServerObjects.ASimpleModel, abort?: AbortSignal): Promise<ServerObjects.ASimpleModel> {
	return fetchWrapper("GET", `/Home/FunctionWithModel?param1=val1&param2=val2`, model, abort);
}

/**
 * 
 * @param model 
 */
export function MultipleFromStuff(model: ServerObjects.ASimpleModel, abort?: AbortSignal): Promise<ServerObjects.ASimpleModel> {
	return fetchWrapper("POST", `/Home/MultipleFromStuff?param1=val1&param2=val2`, model, abort);
}

/**
 * 
 */
export function NoFromBodyParams(abort?: AbortSignal): Promise<ServerObjects.ASimpleModel> {
	return fetchWrapper("GET", `/Home/NoFromBodyParams?param1=val1&param2=val2`, null, abort);
}

/**
 * 
 * @param model 
 */
export function OtherFunctionWithModel(model: CustomGroup.CustomGroupObject1, abort?: AbortSignal): Promise<CustomGroup.CustomGroupObject1> {
	return fetchWrapper("GET", `/Home/OtherFunctionWithModel?param1=val1&param2=val2`, model, abort);
}

/**
 * 
 */
export function TestJson(abort?: AbortSignal): Promise<ServerObjects.NetStandardClass> {
	return fetchWrapper("GET", `/Home/TestJson?param1=val1&param2=val2`, null, abort);
}

