// File Autogenerated by TypeRight.  DO NOT EDIT
import { fetchWrapper } from "../CallServiceStuff";
import * as CustomGroup from "../CustomGroup";
import * as ServerObjects from "../ServerObjects";
import * as Models from "./Models";

function tryAppendKeyValueToUrl(urlParams: URLSearchParams, key: string, value: any): void {
    if (value !== null && typeof value !== "undefined") {
        if (Array.isArray(value)) {
            for (let aryVal of value) {
                urlParams.append(key, aryVal.toString());
            }
        } else {
            urlParams.append(key, value);
        }
    }
}

function getQueryString(urlParams: URLSearchParams): string {
    let queryString = urlParams.toString();
    if (queryString !== "") {
        queryString = "?" + queryString;
    }
    return queryString;
}

/**
 * 
 * @param model 
 */
export function AnonTypeWithDictionaryProperty(model: Models.CustomGroupObj3, abort?: AbortSignal): Promise<{ listObj: CustomGroup.CustomGroupObject1[] }> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("GET", `/Home/AnonTypeWithDictionaryProperty${getQueryString(urlParams)}`, model, abort);
}

/**
 * 
 * @param model 
 */
export function FunctionWithModel(model: ServerObjects.ASimpleModel, abort?: AbortSignal): Promise<ServerObjects.ASimpleModel> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("GET", `/Home/FunctionWithModel${getQueryString(urlParams)}`, model, abort);
}

/**
 * 
 * @param model 
 */
export function MultipleFromStuff(model: ServerObjects.ASimpleModel, abort?: AbortSignal): Promise<ServerObjects.ASimpleModel> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("POST", `/Home/MultipleFromStuff${getQueryString(urlParams)}`, model, abort);
}

/**
 * 
 */
export function NoFromBodyParams(abort?: AbortSignal): Promise<ServerObjects.ASimpleModel> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("GET", `/Home/NoFromBodyParams${getQueryString(urlParams)}`, null, abort);
}

/**
 * 
 * @param model 
 */
export function OtherFunctionWithModel(model: CustomGroup.CustomGroupObject1, abort?: AbortSignal): Promise<CustomGroup.CustomGroupObject1> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("GET", `/Home/OtherFunctionWithModel${getQueryString(urlParams)}`, model, abort);
}

/**
 * 
 */
export function TestJson(abort?: AbortSignal): Promise<ServerObjects.NetStandardClass> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("GET", `/Home/TestJson${getQueryString(urlParams)}`, null, abort);
}

