// File Autogenerated by TypeRight.  DO NOT EDIT
import * as CustomGroup from "../CustomGroup";
import * as ServerObjects from "../ServerObjects";

// ===============================
// Classes
// ===============================
/**  */
export interface CustomGroupObj3 {
	/**  */
	StringProp: string;
	/**  */
	Obj1: CustomGroup.CustomGroupObject1;
	/**  */
	GenericArg: CustomGroup.CustomGroupObj2_1<ServerObjects.NetStandardEnum>;
}

  

// ===============================
// Enums
// ===============================
  