// File Autogenerated by TypeRight.  DO NOT EDIT
import { callPost } from "../CallServiceStuff";
import * as CustomGroup from "../CustomGroup";


/**
 * 
 * @param id 
 */
export function GetRandoGroupObject(id: string, abort?: AbortSignal): Promise<CustomGroup.CustomGroupObject1> {
	return callPost("/api/TestWebApi/GetRandoGroupObject", id, abort);
}

/**
 * 
 */
export function GetStringList(abort?: AbortSignal): Promise<string[]> {
	return callPost("/api/TestWebApi/GetStringList", { }, abort);
}


