// File Autogenerated by TypeRight.  DO NOT EDIT
import { callPost, callGet, callPut } from "../CallServiceStuff";
/**
 *
 * @param id
 */
export function GetRandoGroupObject(id, abort) {
    return callPost(`/api/TestWebApi/GetRandoGroupObject`, id, abort);
}
/**
 *
 * @param id
 */
export function GetSomething(id, abort) {
    return callGet(`/api/TestWebApi/things/${id}/action`, abort);
}
/**
 *
 */
export function GetStringList(abort) {
    return callPost(`/api/TestWebApi/GetStringList`, {}, abort);
}
/**
 *
 * @param id
 * @param body
 */
export function PutSomething(id, body, abort) {
    return callPut(`/api/TestWebApi/things/${id}/action`, body, abort);
}
/**
 *
 */
export function TestActionResult(abort) {
    return callPost(`/api/TestWebApi/TestActionResult`, {}, abort);
}
/**
 *
 */
export function TestClassActionResult(abort) {
    return callPost(`/api/TestWebApi/TestClassActionResult`, {}, abort);
}
/**
 *
 * @param id
 */
export function TestGetMethod(id, abort) {
    return callGet(`/api/TestWebApi/TestGetMethod?id=${id}`, abort);
}
/**
 *
 * @param id
 * @param body
 */
export function WithFromQuery(id, body, abort) {
    return callPost(`/api/TestWebApi/WithFromQuery?id=${id}`, body, abort);
}
//# sourceMappingURL=TestWebApiActions.js.map