// File Autogenerated by TypeRight.  DO NOT EDIT
import { callPost } from "../CallServiceStuff";
/**
 *
 * @param id
 */
export function GetRandoGroupObject(id, abort) {
    return callPost("/api/TestWebApi/GetRandoGroupObject", id, abort);
}
/**
 *
 */
export function GetStringList(abort) {
    return callPost("/api/TestWebApi/GetStringList", {}, abort);
}
//# sourceMappingURL=TestWebApiActions.js.map