// File Autogenerated by TypeRight.  DO NOT EDIT
import { callPost, callGet } from "../CallServiceStuff";
/**
 *
 * @param id
 */
export function GetRandoGroupObject(id, abort) {
    return callPost(`/api/TestWebApi/GetRandoGroupObject`, id, abort);
}
/**
 *
 */
export function GetStringList(abort) {
    return callPost(`/api/TestWebApi/GetStringList`, {}, abort);
}
/**
 *
 * @param id
 */
export function TestGetMethod(id, abort) {
    return callGet(`/api/TestWebApi/TestGetMethod?id=${id}`, abort);
}
/**
 *
 * @param id
 * @param body
 */
export function WithFromQuery(id, body, abort) {
    return callPost(`/api/TestWebApi/WithFromQuery?id=${id}`, body, abort);
}
//# sourceMappingURL=TestWebApiActions.js.map