// File Autogenerated by TypeRight.  DO NOT EDIT
var ServerEnums;
(function (ServerEnums) {
    /**  */
    var ExampleEnum;
    (function (ExampleEnum) {
        /**  */
        ExampleEnum[ExampleEnum["One"] = 0] = "One";
        /**  */
        ExampleEnum[ExampleEnum["Two"] = 1] = "Two";
        /**  */
        ExampleEnum[ExampleEnum["Three"] = 2] = "Three";
    })(ExampleEnum = ServerEnums.ExampleEnum || (ServerEnums.ExampleEnum = {}));
})(ServerEnums || (ServerEnums = {}));
//# sourceMappingURL=ServerObjects.js.map