// File Autogenerated by TypeRight.  DO NOT EDIT
import { fetchWrapper } from "../Communication";


/**
 * 
 */
export function Privacy(abort?: AbortSignal): Promise<any> {
	return fetchWrapper("GET", `/Home/Privacy`, null, abort);
}

