using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using TypeRight.Configuration;
using TypeRight.ScriptWriting;
using TypeRight.Tests.TestBuilders;
using TypeRight.Tests.Testers;

namespace TypeRight.Tests.Controllers
{
	public abstract class ControllerTestsBase : TypeRightTestBase
	{
		private ConfigOptions _configOptions;

		protected TestClassBuilder ControllerBuilder { get; private set; }

		protected string ControllerFullName => "TestController";
		protected string ControllerName => "Test";

		protected abstract bool IsAspNetCore { get; }

		[TestInitialize]
		public override void TestInitialize()
		{
			base.TestInitialize();

			_configOptions = new ConfigOptions()
			{
				ActionConfigurations = TypeCollectionTester.GetDefaultActionConfig(),
				QueryParams = new NameValueCollection()
			};

			GivenActionParameters(Array.Empty<ActionParameter>());

			WorkspaceBuilder.DefaultProject
				.AddFakeMvc();

			// Test class to use as return/param
			AddClass("TestClass")
				.AddScriptObjectAttribute()
				.AddProperty("DontCare", "int")
				.Commit();

			// Test generic class to use as return/param
			AddClass("TestGenericClass")
				.AddScriptObjectAttribute()
				.AddGenericParameter("T")
				.AddProperty("GenericProp", "T")
				.Commit();

			ControllerBuilder = AddClass(ControllerFullName)
				.WithControllerBaseClass(IsAspNetCore)

				// Fake Json method
				.AddMethod("Json", IsAspNetCore ? MvcConstants.JsonResult_AspNetCore : MvcConstants.JsonResult_AspNet)
					.AddParameter("data", "object")
					.AddLineOfCode("return null;", 0)
					.Commit();
		}

		protected TestMethodBuilder AddControllerAction(string name, string returnType)
		{
			return ControllerBuilder.AddMethod(name, returnType).AddScriptActionAttribute();
		}

		protected void GivenImportDefinition(ImportDefinition definition)
		{
			_configOptions.ActionConfigurations[0].Imports.Add(definition);
		}

		protected void GivenActionParameters(IEnumerable<ActionParameter> actionParameters)
		{
			_configOptions.ActionConfigurations[0].Parameters = actionParameters.ToList();
		}

		protected void GivenActionConfig(ActionConfig config)
		{
			_configOptions.ActionConfigurations.Add(config);
		}

		protected void GivenQueryParameter(string key, string value)
		{
			_configOptions.QueryParams.Add(key, value);
		}

		protected void GivenBaseUrl(string url) => _configOptions.BaseUrl = url;

		protected void GivenFetchConfig(FetchConfig fetchConfig)
		{
			_configOptions.ActionConfigurations = null;
			_configOptions.FetchConfig = fetchConfig;
		}

		protected void AddFetchConfigParameter(ActionParameter actionParam)
		{
			_configOptions.FetchConfig.Parameters.Add(actionParam);
		}

		protected void GivenScriptReturnType(string returnType) => _configOptions.ActionConfigurations[0].ReturnType = returnType;

		protected MvcActionTester AssertThatThisControllerAction(string actionName)
		{
			return AssertThatThisController().TestActionWithName(actionName);
		}

		protected ControllerTester AssertThatThisController()
		{
			var packageTester = CreateTester();
			return packageTester.TestControllerWithName(ControllerFullName, CreateContext(packageTester));
		}

		protected void AssertControllerGeneratedText(string expectedText)
		{
			ControllerBuilder.Commit();

			var packageTester = WorkspaceBuilder.GetPackageTester();
			var context = CreateContext(packageTester);

			expectedText = "// File Autogenerated by TypeRight.  DO NOT EDIT\r\n" + expectedText.Trim();

			packageTester.AssertControllerScriptText(context, expectedText);
		}

		private ControllerContext CreateContext(TypeCollectionTester tester)
		{
			return tester.GetDefaultControllerContext(ControllerFullName, _configOptions);
		}

		private TypeCollectionTester CreateTester()
		{
			ControllerBuilder.Commit();
			return WorkspaceBuilder.GetPackageTester();

		}
	}
}
