// File Autogenerated by TypeRight.  DO NOT EDIT
import * as CustomGroup from "../CustomGroup.js";

// ===============================
// Classes
// ===============================
/**  */
export interface CustomGroupObj3 {
	/**  */
	stringProp: string;
	/**  */
	obj1: CustomGroup.CustomGroupObject1;
}

  

// ===============================
// Enums
// ===============================
  