// File Autogenerated by TypeRight.  DO NOT EDIT
var WebMethods;
(function (WebMethods) {
    var Home;
    (function (Home) {
        /**
         *
         * @param dict
         */
        function Test_Anonymous(dict, success, fail) {
            Comm.callService("/Home/Test_Anonymous", { dict: dict }, success, fail);
        }
        Home.Test_Anonymous = Test_Anonymous;
        /**
         *
         * @param example
         */
        function Test_ObjectParam(example, success, fail) {
            Comm.callService("/Home/Test_ObjectParam", { example: example }, success, fail);
        }
        Home.Test_ObjectParam = Test_ObjectParam;
        /**
         *
         * @param dict
         */
        function Test_ObjectReturn(dict, success, fail) {
            Comm.callService("/Home/Test_ObjectReturn", { dict: dict }, success, fail);
        }
        Home.Test_ObjectReturn = Test_ObjectReturn;
        /**
         *
         */
        function TestJson(success, fail) {
            Comm.callService("/Home/TestJson", {}, success, fail);
        }
        Home.TestJson = TestJson;
    })(Home = WebMethods.Home || (WebMethods.Home = {}));
})(WebMethods || (WebMethods = {}));
//# sourceMappingURL=HomeActions.js.map