"use strict";
// File Autogenerated by TypeRight.  DO NOT EDIT
Object.defineProperty(exports, "__esModule", { value: true });
var CallServiceStuff_1 = require("../CallServiceStuff");
/**
 *
 * @param dict
 */
function Test_Anonymous(dict, success, fail) {
    CallServiceStuff_1.callService("/Home/Test_Anonymous", { dict: dict }, success, fail);
}
exports.Test_Anonymous = Test_Anonymous;
/**
 *
 * @param example
 */
function Test_ObjectParam(example, success, fail) {
    CallServiceStuff_1.callService("/Home/Test_ObjectParam", { example: example }, success, fail);
}
exports.Test_ObjectParam = Test_ObjectParam;
/**
 *
 * @param dict
 */
function Test_ObjectReturn(dict, success, fail) {
    CallServiceStuff_1.callService("/Home/Test_ObjectReturn", { dict: dict }, success, fail);
}
exports.Test_ObjectReturn = Test_ObjectReturn;
/**
 *
 */
function TestJson(success, fail) {
    CallServiceStuff_1.callService("/Home/TestJson", {}, success, fail);
}
exports.TestJson = TestJson;
//# sourceMappingURL=HomeActions.js.map