// File Autogenerated by TypeRight.  DO NOT EDIT

namespace ServerClasses {
	/** Hey.  Here are some docs */
	export interface Class1 {
		/** This is a property */
		ExtractDependent: number;
	}

	/**  */
	export interface ExampleClass {
		/** Doc for int - i did it yea more comments more */
		IntProperty: number;
		/** String list! more! no more ya hey hi no */
		StringList: string[];
		/** Adding documentation for this class hey, yo hola */
		AnotherPropertyYea: number;
		/** Another */
		BooleanProp: boolean;
		/** new thing again */
		Hey: number;
		/**  */
		AddedProp: number;
	}

	/**  */
	export interface Extends extends ServerClasses.ExampleClass {
		/**  */
		OneMoreProp: number;
	}

	/**  */
	export interface FileInfo {
		/**  */
		Name: string;
		/**  */
		Length: number;
		/**  */
		DirectoryName: string;
		/**  */
		Directory: any;
		/**  */
		IsReadOnly: boolean;
		/**  */
		Exists: boolean;
		/**  */
		FullName: string;
		/**  */
		Extension: string;
		/**  */
		CreationTime: string;
		/**  */
		CreationTimeUtc: string;
		/**  */
		LastAccessTime: string;
		/**  */
		LastAccessTimeUtc: string;
		/**  */
		LastWriteTime: string;
		/**  */
		LastWriteTimeUtc: string;
		/**  */
		Attributes: number;
	}

  
}
  

namespace ServerEnums {
	/**  */
	export enum ExampleEnum {
		/**  */
		One = 0,
		/**  */
		Two = 1,
		/**  */
		Three = 2,
	}
  
}
  