// File Autogenerated by TypeRight.  DO NOT EDIT

// ===============================
// Classes
// ===============================
/**  */
export interface Class1 {
	/**  */
	ExtractDependent: number;
}

/**  */
export interface ExampleClass {
	/** Doc for int - i did it yea more comments more */
	IntProperty: number;
	/** String list! more! no more ya hey hi no */
	StringList: string[];
	/** Adding documentation for this class hey, yo hola */
	AnotherPropertyYea: number;
	/** Another */
	BooleanProp: boolean;
	/** new thing again */
	Hey: number;
	/**  */
	AddedProp: number;
}

/**  */
export interface Extends extends ExampleClass {
	/**  */
	OneMoreProp: number;
}

  

// ===============================
// Enums
// ===============================

/**  */
export enum ExampleEnum {
	/**  */
	One = 0,
	/**  */
	Two = 1,
	/**  */
	Three = 2,
}
 

  