// File Autogenerated by TypeRight.  DO NOT EDIT
import * as ServerObjects from "./ServerObjects";

// ===============================
// Classes
// ===============================
/**  */
export interface ASimpleModel<T1, T2> {
	/**  */
	reference: ServerObjects.ASimpleModel_1<T1>;
	/**  */
	ahDoesThisWork: ASimpleEnum;
	/**  */
	referenceArray: ServerObjects.ASimpleModel_1<T1>[];
	/**  */
	referenceList: ServerObjects.ASimpleModel_1<T1>[];
	/**  */
	enumDict: { [key: number]: ServerObjects.NetStandardEnum };
	/**  */
	nullableEnum: ServerObjects.NetStandardEnum;
}

/**  */
export interface CustomGroupObj2 {
	/**  */
	obj1: CustomGroupObject1;
}

/**  */
export interface CustomGroupObj2_1<T> {
	/**  */
	property: number;
}

/**  */
export interface CustomGroupObject1 {
	/** Add doc */
	prop1: number;
	/**  */
	otherClass: ServerObjects.NetStandardClass;
	/** Just has a string list */
	anotherStringList: string[];
}

  

// ===============================
// Enums
// ===============================
/**  */
export enum ASimpleEnum {
	/**  */
	A = 0,
	/**  */
	B = 1,
	/**  */
	C = 2,
}

  