// File Autogenerated by TypeRight.  DO NOT EDIT
import { fetchWrapper } from "./CallServiceStuff";

function tryAppendKeyValueToUrl(urlParams: URLSearchParams, key: string, value: any): void {
    if (value !== null && typeof value !== "undefined") {
        if (Array.isArray(value)) {
            for (let aryVal of value) {
                urlParams.append(key, aryVal.toString());
            }
        } else {
            urlParams.append(key, value);
        }
    }
}

function getQueryString(urlParams: URLSearchParams): string {
    let queryString = urlParams.toString();
    if (queryString !== "") {
        queryString = "?" + queryString;
    }
    return queryString;
}

/**
 * 
 * @param id 
 */
export function DeleteFirst(id: number, abort?: AbortSignal): Promise<any> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("DELETE", `/api/FirstGrouped/${id}${getQueryString(urlParams)}`, null, abort);
}

/**
 * 
 * @param id 
 */
export function DeleteSecond(id: number, abort?: AbortSignal): Promise<any> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("DELETE", `/api/SecondGrouped/${id}${getQueryString(urlParams)}`, null, abort);
}

/**
 * 
 */
export function GetFirst(abort?: AbortSignal): Promise<string[]> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("GET", `/api/FirstGrouped${getQueryString(urlParams)}`, null, abort);
}

/**
 * 
 * @param id 
 */
export function GetFirstById(id: number, abort?: AbortSignal): Promise<string> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("GET", `/api/FirstGrouped/${id}${getQueryString(urlParams)}`, null, abort);
}

/**
 * 
 */
export function GetSecond(abort?: AbortSignal): Promise<string[]> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("GET", `/api/SecondGrouped${getQueryString(urlParams)}`, null, abort);
}

/**
 * 
 * @param id 
 */
export function GetSecondById(id: number, abort?: AbortSignal): Promise<string> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("GET", `/api/SecondGrouped/${id}${getQueryString(urlParams)}`, null, abort);
}

/**
 * 
 * @param value 
 */
export function PostFirst(value: string, abort?: AbortSignal): Promise<any> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("POST", `/api/FirstGrouped${getQueryString(urlParams)}`, value, abort);
}

/**
 * 
 * @param value 
 */
export function PostSecond(value: string, abort?: AbortSignal): Promise<any> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("POST", `/api/SecondGrouped${getQueryString(urlParams)}`, value, abort);
}

/**
 * 
 * @param id 
 * @param value 
 */
export function PutFirst(id: number, value: string, abort?: AbortSignal): Promise<any> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("PUT", `/api/FirstGrouped/${id}${getQueryString(urlParams)}`, value, abort);
}

/**
 * 
 * @param id 
 * @param value 
 */
export function PutSecond(id: number, value: string, abort?: AbortSignal): Promise<any> {
	let urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("PUT", `/api/SecondGrouped/${id}${getQueryString(urlParams)}`, value, abort);
}

