// File Autogenerated by TypeRight.  DO NOT EDIT

// ===============================
// Classes
// ===============================
/** Tst model */
export interface ASimpleModel {
	/** Doc for prop 1 */
	PropOne: number;
	/** Doc for prop 2 */
	PropTwo: string;
	/**  */
	overrideSysText: number;
	/**  */
	overrideNewtonsoft: number;
	/**  */
	NoNewtonsoftOverride: number;
}

/**  */
export interface ASimpleModel_1<T> {
	/**  */
	GenericThing: T;
}

/**  */
export interface CommandResult {
	/**  */
	Success: boolean;
	/**  */
	ErrorMessage: string;
}

/**  */
export interface CommandResult_1<T> extends CommandResult {
	/**  */
	Result: T;
}

/** Test summ */
export interface ErrorViewModel {
	/**  */
	RequestId: string;
	/**  */
	ShowRequestId: boolean;
}

/**  */
export interface GenericModel<T> {
	/**  */
	Prop1: T;
}

/** Start some doc here */
export interface NetStandardClass {
	/**  */
	HelloThere: number;
	/**  */
	EnumType: NetStandardEnum;
}

/**  */
export interface TestTwoTypeParams<T, T2> {
	/**  */
	Prop1: T;
	/**  */
	Prop2: T2;
}

  

// ===============================
// Enums
// ===============================
/**  */
export enum NetStandardEnum {
	/**  */
	One = 0,
	/**  */
	Two = 1,
	/**  */
	Three = 2,
}

  