// File Autogenerated by TypeRight.  DO NOT EDIT
import * as CustomGroup from "./CustomGroup";

// ===============================
// Classes
// ===============================
/**  */
export interface AGenericTypeHere<T> {
	/**  */
	notNull: T;
	/**  */
	nullable: T | null;
}

/**  */
export interface ANullableModel {
	/** int? */
	propOne: number | null;
	/** string? */
	propTwo: string | null;
	/** ASimpleEnum? */
	nullableEnum: CustomGroup.ASimpleEnum | null;
	/** ASimpleModel? */
	nullableRefType: ASimpleModel | null;
	/** List[int]? */
	nullableList: number[] | null;
	/** List[int?]? */
	nullableListNullElement: (number | null)[] | null;
	/** int[]? */
	nullableArray: number[] | null;
	/** int?[]? */
	nullableArrayNullElement: (number | null)[] | null;
	/** ASimpleModel[]? */
	nullableArrayRefTypeElement: ASimpleModel[] | null;
	/** Dictionary[int, ASimpleModel?] */
	dictionaryNullValue: { [key: number]: ASimpleModel | null };
	/** AGenericTypeHere[int] */
	genericNotNull: AGenericTypeHere<number>;
	/** AGenericTypeHere[int?] */
	genericNullable: AGenericTypeHere<number | null>;
}

/**
 * Tst model
 * with two line comment
 */
export interface ASimpleModel {
	/** Doc for prop 1 */
	propOne: number;
	/**
	 * Doc for prop 2
	 * With another line!
	 */
	propTwo: string;
	/**  */
	overrideSysText: number;
	/**  */
	overrideNewtonsoft: number;
	/**  */
	noNewtonsoftOverride: number;
}

/**  */
export interface ASimpleModel_1<T> {
	/**  */
	genericThing: T;
}

/**  */
export interface CommandResult {
	/**  */
	success: boolean;
	/**  */
	errorMessage: string;
}

/**  */
export interface CommandResult_1<T> extends CommandResult {
	/**  */
	result: T;
}

/**  */
export interface DatesAndTimes {
	/**  */
	dateTimeProp: string;
	/**  */
	dateOnlyProp: string;
	/**  */
	timeOnlyProp: string;
	/**  */
	dateTimeOffsetProp: string;
}

/** Test summ */
export interface ErrorViewModel {
	/**  */
	requestId: string;
	/**  */
	showRequestId: boolean;
}

/**  */
export interface GenericModel<T> {
	/**  */
	prop1: T;
}

/**  */
export interface ModelWithArray {
	/**  */
	simpleType: string;
	/**  */
	arrayType: number[];
}

/** Start some doc here */
export interface NetStandardClass {
	/**  */
	helloThere: number;
	/**  */
	enumType: NetStandardEnum;
}

/**  */
export interface TestTwoTypeParams<T, T2> {
	/**  */
	prop1: T;
	/**  */
	prop2: T2;
}

  

// ===============================
// Enums
// ===============================
/**  */
export enum NetStandardEnum {
	/**  */
	One = 0,
	/**  */
	Two = 1,
	/**  */
	Three = 2,
}

  