// File Autogenerated by TypeRight.  DO NOT EDIT
import { fetchWrapper } from "./CallServiceStuff.js";

function tryAppendKeyValueToUrl(urlParams: URLSearchParams, key: string, value: any): void {
    if (value !== null && typeof value !== "undefined") {
        if (Array.isArray(value)) {
            for (let aryVal of value) {
                urlParams.append(key, aryVal.toString());
            }
        } else {
            urlParams.append(key, value);
        }
    }
}

function getQueryString(urlParams: URLSearchParams): string {
    let queryString = urlParams.toString();
    if (queryString !== "") {
        queryString = "?" + queryString;
    }
    return queryString;
}

/**
 * 
 */
export function getWithAdditionalPropParam(id: number, other: string, abort?: AbortSignal): Promise<string> {
	const urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("GET", `/api/PropRouteParams/${id}/some-thing/get/${other}/thing${getQueryString(urlParams)}`, null, abort);
}

/**
 * 
 * @param fromMethod 
 */
export function getWithEverything(id: number, other: string, fromMethod: number, abort?: AbortSignal): Promise<string> {
	const urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("GET", `/api/PropRouteParams/${id}/some-thing/thing/${other}/${fromMethod}/yea${getQueryString(urlParams)}`, null, abort);
}

/**
 * 
 * @param fromMethod 
 */
export function getWithMethodParam(id: number, fromMethod: number, abort?: AbortSignal): Promise<string> {
	const urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("GET", `/api/PropRouteParams/${id}/some-thing/thing/${fromMethod}/yea${getQueryString(urlParams)}`, null, abort);
}

/**
 * 
 */
export function getWithoutAdditionalPropParam(id: number, abort?: AbortSignal): Promise<string> {
	const urlParams = new URLSearchParams();
	tryAppendKeyValueToUrl(urlParams, "param1", "val1");
	tryAppendKeyValueToUrl(urlParams, "param2", "val2");
	return fetchWrapper("GET", `/api/PropRouteParams/${id}/some-thing/thing${getQueryString(urlParams)}`, null, abort);
}

