using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using TypeRight.Configuration;
using TypeRight.ScriptWriting;
using TypeRight.TypeProcessing;
using TypeRight.Workspaces.Parsing;
using TypeRight.Tests.TestBuilders;
using TypeRight.Tests.Testers;

namespace TypeRight.Tests.ScrpitWriting
{
	[TestClass]
	public class ScriptWritingTests
	{

		private static TypeCollectionTester s_packageTester;

		/// <summary>
		/// Sets up a parse of this solution
		/// </summary>
		[ClassInitialize]
		public static void SetupParse(TestContext context)
		{

			TestWorkspaceBuilder wkspBuilder = new TestWorkspaceBuilder();

			wkspBuilder.DefaultProject
				.AddFakeTypeRight()
				.AddFakeMvc()

				// Test class to use as return/param
				.CreateClassBuilder("TestClass")
					.AddScriptObjectAttribute()
					.AddProperty("DontCare", "int")
					.Commit()

				// Test generic class to use as return/param
				.CreateClassBuilder("TestGenericClass")
					.AddScriptObjectAttribute()
					.AddGenericParameter("T")
					.AddProperty("GenericProp", "T")
					.Commit()
					

				.CreateClassBuilder("TestParamAttributesController")
					.WithControllerBaseClass()
					.AddMethod("TestingParamFilter", MvcConstants.JsonResult_AspNetCore)
						.AddScriptActionAttribute()
						.AddParameter("fromBody", "string", attribute: MvcConstants.FromBodyAttributeFullName_AspNetCore)
						.AddParameter("fromServices", "TestClass", attribute: MvcConstants.FromServicesAttributeFullName_AspNetCore)
						.AddLineOfCode("return Json(0);", 0)
						.Commit()
					.AddMethod("IsNotFirstParameter", MvcConstants.JsonResult_AspNetCore)
						.AddScriptActionAttribute()
						.AddParameter("fromServices", "TestClass", attribute: MvcConstants.FromServicesAttributeFullName_AspNetCore)
						.AddParameter("fromBody", "string", attribute: MvcConstants.FromBodyAttributeFullName_AspNetCore)
						.AddLineOfCode("return Json(0);", 0)
						.Commit()
					.AddMethod("NoFromBodyParams", MvcConstants.JsonResult_AspNetCore)
						.AddScriptActionAttribute()
						.AddParameter("fromServices", "TestClass", attribute: MvcConstants.FromServicesAttributeFullName_AspNetCore)
						.AddParameter("fromServices2", "string", attribute: MvcConstants.FromServicesAttributeFullName_AspNetCore)
						.AddParameter("fromServices3", "string", attribute: MvcConstants.FromServicesAttributeFullName_AspNetCore)
						.AddLineOfCode("return Json(0);", 0)
						.Commit()
					.AddMethod("QueryParameterWithBody", MvcConstants.JsonResult_AspNetCore)
						.AddScriptActionAttribute()
						.AddParameter("fromQuery", "string", attribute: MvcConstants.FromQueryAttributeFullName_AspNetCore)
						.AddParameter("fromBody", "TestClass", attribute: MvcConstants.FromBodyAttributeFullName_AspNetCore)
						.Commit()
					.Commit()

				.CreateClassBuilder("RoutedApiController")
					.WithControllerBaseClass()
					.AddAttribute(MvcConstants.RouteAttributeFullName_AspNetCore)
						.AddConstructorArg("\"api/RoutedApi\"")
						.Commit()
					.AddMethod("GetThing", "string")
						.AddScriptActionAttribute()
						.AddAttribute(MvcConstants.HttpGetAttributeFullName_AspNetCore)
							.AddConstructorArg("\"thing/{thingId}\"").Commit()
						.AddParameter("thingId", "string")
						.AddLineOfCode("return null", 0)
						.Commit()
					.AddMethod("PutThingWithQuery", "string")
						.AddScriptActionAttribute()
						.AddAttribute(MvcConstants.HttpPutAttributeFullName_AspNetCore)
							.AddConstructorArg("\"thing/{thingId}/put\"").Commit()
						.AddParameter("thingId", "string")
						.AddParameter("query", "string", attribute: MvcConstants.FromQueryAttributeFullName_AspNetCore)
						.AddParameter("body", "bool", attribute: MvcConstants.FromBodyAttributeFullName_AspNetCore)
						.AddLineOfCode("return null", 0)
						.Commit()
					.AddMethod("DeleteThing", "string")
						.AddScriptActionAttribute()
						.AddAttribute(MvcConstants.ToAspNetCoreFullName(MvcConstants.HttpDeleteAttributeName))
							.AddConstructorArg("\"thing/{thingId}\"").Commit()
						.AddParameter("thingId", "string")
						.AddLineOfCode("return null", 0)
						.Commit()
					.Commit()
			;
			
			s_packageTester = wkspBuilder.GetPackageTester();
		}

		[TestMethod]
		public void Controllers_ExcludingNonFromBodyParameters()
		{
			var actionConfig = s_packageTester.GetDefaultActionConfig();
			actionConfig[0].Parameters = new List<ActionParameter>();   // clear out for simplicity
			ControllerContext context = s_packageTester.GetDefaultControllerContext(actionConfig);
			s_packageTester.AssertControllerScriptText("TestParamAttributesController",
				context,
			#region ScriptText	
				@"
// File Autogenerated by TypeRight.  DO NOT EDIT
import * as DefaultResult from ""../../DefaultResult"";
import { TestAjax } from ""../../FolderM/FolderN/AjaxFunc"";


/**
 * 
 * @param fromBody 
 */
export function IsNotFirstParameter(fromBody: string): void {
	TestAjax(`/TestParamAttributes/IsNotFirstParameter`, fromBody);
}

/**
 * 
 */
export function NoFromBodyParams(): void {
	TestAjax(`/TestParamAttributes/NoFromBodyParams`, {});
}

/**
 * 
 * @param fromQuery 
 * @param fromBody 
 */
export function QueryParameterWithBody(fromQuery: string, fromBody: DefaultResult.TestClass): void {
	TestAjax(`/TestParamAttributes/QueryParameterWithBody?fromQuery=${ fromQuery ?? """" }`, fromBody);
}

/**
 * 
 * @param fromBody 
 */
export function TestingParamFilter(fromBody: string): void {
	TestAjax(`/TestParamAttributes/TestingParamFilter`, fromBody);
}


"
			#endregion
				);
		}

		[TestMethod]
		public void Controllers_RoutedApiController()
		{
			var actionConfig = s_packageTester.GetDefaultActionConfig();
			actionConfig[0].Parameters = new List<ActionParameter>();   // clear out for simplicity
			ControllerContext context = s_packageTester.GetDefaultControllerContext(actionConfig);
			s_packageTester.AssertControllerScriptText("RoutedApiController",
				context,
			#region ScriptText	
				@"
// File Autogenerated by TypeRight.  DO NOT EDIT
import { TestAjax, callDelete } from ""../../FolderM/FolderN/AjaxFunc"";


/**
 * 
 * @param thingId 
 */
export function DeleteThing(thingId: string): void {
	callDelete(`/api/RoutedApi/thing/${thingId}`);
}

/**
 * 
 * @param thingId 
 */
export function GetThing(thingId: string): void {
	TestAjax(`/api/RoutedApi/thing/${thingId}`);
}

/**
 * 
 * @param thingId 
 * @param query 
 * @param body 
 */
export function PutThingWithQuery(thingId: string, query: string, body: boolean): void {
	TestAjax(`/api/RoutedApi/thing/${thingId}/put?query=${ query ?? """" }`, body);
}

"
			#endregion
				);
		}

		[TestMethod]
		public void Scripts_ExtendsBaseType_WithSameName_DiffTypeParams()
		{
			TestWorkspaceBuilder builder = new TestWorkspaceBuilder();

			builder.DefaultProject
				.AddFakeTypeRight()
				.CreateClassBuilder("MyType")
					.AddScriptObjectAttribute()
					.AddProperty("BaseProperty", "string")
					.Commit()
				.CreateClassBuilder("MyType")
					.AddScriptObjectAttribute()
					.AddGenericParameter("T")
					.AddBaseClass("MyType")
					.AddProperty("GenericProp", "T")
					.Commit()
				;

			TypeCollectionTester tcTester = builder.GetPackageTester();
			tcTester.AssertScriptText(@"
// File Autogenerated by TypeRight.  DO NOT EDIT

// ===============================
// Classes
// ===============================
/**  */
export interface MyType {
	/**  */
	BaseProperty: string;
}

/**  */
export interface MyType_1<T> extends MyType {
	/**  */
	GenericProp: T;
}

  

// ===============================
// Enums
// ===============================

");

		}
		
	}
}
