// File Autogenerated by TypeRight.  DO NOT EDIT

namespace WebMethods.HomeController {

	/**
	 * 
	 * @param dict 
	 */
	export function Test_Anonymous(dict: { [key: string]: string }): void {
		Comm.callService(`/Home/Test_Anonymous`, { dict: dict });
	}
	
	/**
	 * 
	 * @param example 
	 */
	export function Test_ObjectParam(example: ServerClasses.ExampleClass): void {
		Comm.callService(`/Home/Test_ObjectParam`, { example: example });
	}
	
	/**
	 * 
	 * @param dict 
	 */
	export function Test_ObjectReturn(dict: { [key: string]: string }): void {
		Comm.callService(`/Home/Test_ObjectReturn`, { dict: dict });
	}
	
	/**
	 * 
	 */
	export function TestJson(): void {
		Comm.callService(`/Home/TestJson`, {});
	}
	

}