// File Autogenerated by TypeRight.  DO NOT EDIT
// ===============================
// Enums
// ===============================
/**  */
export var NetStandardEnum;
(function (NetStandardEnum) {
    /**  */
    NetStandardEnum[NetStandardEnum["One"] = 0] = "One";
    /**  */
    NetStandardEnum[NetStandardEnum["Two"] = 1] = "Two";
    /**  */
    NetStandardEnum[NetStandardEnum["Three"] = 2] = "Three";
})(NetStandardEnum || (NetStandardEnum = {}));
//# sourceMappingURL=ServerObjects.js.map