name: .NET

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore TypeRight.sln
    - name: Build
      run: dotnet build TypeRight.sln --no-restore
    - name: Test
      run: dotnet test TypeRight.sln --no-build --verbosity normal
