name: .NET

on: [ push ]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Core TypeRight
      run: dotnet build ./src/TypeRight.Build/TypeRight.Build.csproj --no-restore
    - name: Build Tests Project
      run: |
        dotnet build ./test/TypeRight.Tests/TypeRight.Tests.csproj --no-restore
        dotnet build ./test/TypeRight.BuildTests/TypeRight.BuildTests.csproj --no-restore
    - name: Run Unit Tests
      run: dotnet test ./test/TypeRight.Tests/TypeRight.Tests.csproj --no-build --verbosity normal
#    - name: Run Integration Tests
#      run: dotnet test ./test/TypeRight.BuildTests/TypeRight.BuildTests.csproj --no-build --verbosity normal
